display_name: AppRhyme
publisher: CN=2722A838-D7FE-E272-F7DC-C40FF845DD16
publisher_display_name: canxin
identity_name: canxin.app.rhyme
logo_path: assets/log-0.1.0.png 
execution_alias: app_rhyme
install_certificate: false