// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cache.dart';
import 'api/config.dart';
import 'api/http_helper.dart';
import 'api/init.dart';
import 'api/mirror.dart';
import 'api/music_sdk.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0';

  @override
  int get rustContentHash => -1960931803;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_app_rhyme',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiCacheCacheFile(
      {required String file, required String cachePath, String? filename});

  Future<void> crateApiCacheDeleteCacheFile(
      {required String file, required String cachePath, String? filename});

  Future<String> crateApiCacheGenHash({required String str});

  Future<String?> crateApiCacheUseCacheFile(
      {required String file, required String cachePath, String? filename});

  Future<Config> crateApiConfigConfigLoad();

  Future<void> crateApiConfigConfigSave({required Config that});

  Future<String> crateApiHttpHelperSendRequest(
      {required String method,
      required Map<String, String> headers,
      required String url,
      required String payload});

  Future<void> crateApiInitInitApp();

  Future<(SqlMusicFactoryW, Config)> crateApiInitInitStore(
      {required String storeRoot});

  String crateApiMusicSdkMusicWGetExtraInto(
      {required MusicW that, required Quality quality});

  PlatformInt64 crateApiMusicSdkMusicWGetMusicId({required MusicW that});

  MusicInfo crateApiMusicSdkMusicWGetMusicInfo({required MusicW that});

  Future<SqlMusicFactoryW> crateApiMusicSdkSqlMusicFactoryWBuild(
      {required PoolAny pool});

  Future<void> crateApiMusicSdkSqlMusicFactoryWChangeMusicData(
      {required SqlMusicFactoryW that,
      required List<MusicW> musics,
      required List<MusicInfo> infos});

  Future<void> crateApiMusicSdkSqlMusicFactoryWChangeMusicDefaultSource(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required Int64List ids,
      required List<String> defaultSources});

  Future<void> crateApiMusicSdkSqlMusicFactoryWChangeMusicListMetadata(
      {required SqlMusicFactoryW that,
      required List<MusicList> oldList,
      required List<MusicList> newList});

  Future<void> crateApiMusicSdkSqlMusicFactoryWCleanUnusedMusicData(
      {required SqlMusicFactoryW that});

  Future<void> crateApiMusicSdkSqlMusicFactoryWCreateMusicListTable(
      {required SqlMusicFactoryW that, required List<MusicList> musicLists});

  Future<void> crateApiMusicSdkSqlMusicFactoryWDelMusic(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required Int64List ids});

  Future<void> crateApiMusicSdkSqlMusicFactoryWDelMusicListTable(
      {required SqlMusicFactoryW that, required List<MusicList> musicLists});

  Future<void> crateApiMusicSdkSqlMusicFactoryWInitCreateTable(
      {required SqlMusicFactoryW that});

  Future<void> crateApiMusicSdkSqlMusicFactoryWInsertMusic(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required List<MusicW> musics});

  Future<List<MusicW>> crateApiMusicSdkSqlMusicFactoryWReadMusic(
      {required SqlMusicFactoryW that, required MusicList musicList});

  Future<List<MusicW>> crateApiMusicSdkSqlMusicFactoryWReadMusicData(
      {required SqlMusicFactoryW that, required String source});

  Future<List<MusicList>> crateApiMusicSdkSqlMusicFactoryWReadMusicLists(
      {required SqlMusicFactoryW that});

  Future<void> crateApiMusicSdkSqlMusicFactoryWReorderMusic(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required Int64List newIndex,
      required List<MusicW> oldMusicsInOrder});

  Future<List<MusicW>> crateApiMusicSdkGetMusicsFromMusicList(
      {required String payload, required int page, required String source});

  Future<(MusicList, List<MusicW>)> crateApiMusicSdkSearchAlbum(
      {required MusicW music, required int page});

  Future<List<MusicW>> crateApiMusicSdkSearchMusic(
      {required String content, required int page, required String source});

  Future<List<(String, MusicList)>> crateApiMusicSdkSearchMusicList(
      {required String content, required int page, required String source});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_MusicW;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_MusicW;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MusicWPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_PoolAny;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_PoolAny;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PoolAnyPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SqlMusicFactoryW;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SqlMusicFactoryW;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SqlMusicFactoryWPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCacheCacheFile(
      {required String file, required String cachePath, String? filename}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(file, serializer);
        sse_encode_String(cachePath, serializer);
        sse_encode_opt_String(filename, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCacheCacheFileConstMeta,
      argValues: [file, cachePath, filename],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheCacheFileConstMeta => const TaskConstMeta(
        debugName: "cache_file",
        argNames: ["file", "cachePath", "filename"],
      );

  @override
  Future<void> crateApiCacheDeleteCacheFile(
      {required String file, required String cachePath, String? filename}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(file, serializer);
        sse_encode_String(cachePath, serializer);
        sse_encode_opt_String(filename, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCacheDeleteCacheFileConstMeta,
      argValues: [file, cachePath, filename],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheDeleteCacheFileConstMeta =>
      const TaskConstMeta(
        debugName: "delete_cache_file",
        argNames: ["file", "cachePath", "filename"],
      );

  @override
  Future<String> crateApiCacheGenHash({required String str}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(str, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCacheGenHashConstMeta,
      argValues: [str],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheGenHashConstMeta => const TaskConstMeta(
        debugName: "gen_hash",
        argNames: ["str"],
      );

  @override
  Future<String?> crateApiCacheUseCacheFile(
      {required String file, required String cachePath, String? filename}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(file, serializer);
        sse_encode_String(cachePath, serializer);
        sse_encode_opt_String(filename, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCacheUseCacheFileConstMeta,
      argValues: [file, cachePath, filename],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheUseCacheFileConstMeta => const TaskConstMeta(
        debugName: "use_cache_file",
        argNames: ["file", "cachePath", "filename"],
      );

  @override
  Future<Config> crateApiConfigConfigLoad() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_config,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConfigConfigLoadConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigConfigLoadConstMeta => const TaskConstMeta(
        debugName: "config_load",
        argNames: [],
      );

  @override
  Future<void> crateApiConfigConfigSave({required Config that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_config(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiConfigConfigSaveConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigConfigSaveConstMeta => const TaskConstMeta(
        debugName: "config_save",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiHttpHelperSendRequest(
      {required String method,
      required Map<String, String> headers,
      required String url,
      required String payload}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(method, serializer);
        sse_encode_Map_String_String(headers, serializer);
        sse_encode_String(url, serializer);
        sse_encode_String(payload, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHttpHelperSendRequestConstMeta,
      argValues: [method, headers, url, payload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHttpHelperSendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "send_request",
        argNames: ["method", "headers", "url", "payload"],
      );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<(SqlMusicFactoryW, Config)> crateApiInitInitStore(
      {required String storeRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(storeRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_sql_music_factory_w_config,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitInitStoreConstMeta,
      argValues: [storeRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitInitStoreConstMeta => const TaskConstMeta(
        debugName: "init_store",
        argNames: ["storeRoot"],
      );

  @override
  String crateApiMusicSdkMusicWGetExtraInto(
      {required MusicW that, required Quality quality}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            that, serializer);
        sse_encode_box_autoadd_quality(quality, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMusicSdkMusicWGetExtraIntoConstMeta,
      argValues: [that, quality],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkMusicWGetExtraIntoConstMeta =>
      const TaskConstMeta(
        debugName: "MusicW_get_extra_into",
        argNames: ["that", "quality"],
      );

  @override
  PlatformInt64 crateApiMusicSdkMusicWGetMusicId({required MusicW that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMusicSdkMusicWGetMusicIdConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkMusicWGetMusicIdConstMeta =>
      const TaskConstMeta(
        debugName: "MusicW_get_music_id",
        argNames: ["that"],
      );

  @override
  MusicInfo crateApiMusicSdkMusicWGetMusicInfo({required MusicW that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_music_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMusicSdkMusicWGetMusicInfoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkMusicWGetMusicInfoConstMeta =>
      const TaskConstMeta(
        debugName: "MusicW_get_music_info",
        argNames: ["that"],
      );

  @override
  Future<SqlMusicFactoryW> crateApiMusicSdkSqlMusicFactoryWBuild(
      {required PoolAny pool}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
            pool, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWBuildConstMeta,
      argValues: [pool],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWBuildConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_build",
        argNames: ["pool"],
      );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWChangeMusicData(
      {required SqlMusicFactoryW that,
      required List<MusicW> musics,
      required List<MusicInfo> infos}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            musics, serializer);
        sse_encode_list_music_info(infos, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWChangeMusicDataConstMeta,
      argValues: [that, musics, infos],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWChangeMusicDataConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_change_music_data",
        argNames: ["that", "musics", "infos"],
      );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWChangeMusicDefaultSource(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required Int64List ids,
      required List<String> defaultSources}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_box_autoadd_music_list(musicList, serializer);
        sse_encode_list_prim_i_64_strict(ids, serializer);
        sse_encode_list_String(defaultSources, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiMusicSdkSqlMusicFactoryWChangeMusicDefaultSourceConstMeta,
      argValues: [that, musicList, ids, defaultSources],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiMusicSdkSqlMusicFactoryWChangeMusicDefaultSourceConstMeta =>
          const TaskConstMeta(
            debugName: "SqlMusicFactoryW_change_music_default_source",
            argNames: ["that", "musicList", "ids", "defaultSources"],
          );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWChangeMusicListMetadata(
      {required SqlMusicFactoryW that,
      required List<MusicList> oldList,
      required List<MusicList> newList}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_list_music_list(oldList, serializer);
        sse_encode_list_music_list(newList, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiMusicSdkSqlMusicFactoryWChangeMusicListMetadataConstMeta,
      argValues: [that, oldList, newList],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiMusicSdkSqlMusicFactoryWChangeMusicListMetadataConstMeta =>
          const TaskConstMeta(
            debugName: "SqlMusicFactoryW_change_music_list_metadata",
            argNames: ["that", "oldList", "newList"],
          );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWCleanUnusedMusicData(
      {required SqlMusicFactoryW that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWCleanUnusedMusicDataConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiMusicSdkSqlMusicFactoryWCleanUnusedMusicDataConstMeta =>
          const TaskConstMeta(
            debugName: "SqlMusicFactoryW_clean_unused_music_data",
            argNames: ["that"],
          );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWCreateMusicListTable(
      {required SqlMusicFactoryW that, required List<MusicList> musicLists}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_list_music_list(musicLists, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWCreateMusicListTableConstMeta,
      argValues: [that, musicLists],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiMusicSdkSqlMusicFactoryWCreateMusicListTableConstMeta =>
          const TaskConstMeta(
            debugName: "SqlMusicFactoryW_create_music_list_table",
            argNames: ["that", "musicLists"],
          );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWDelMusic(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required Int64List ids}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_box_autoadd_music_list(musicList, serializer);
        sse_encode_list_prim_i_64_strict(ids, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWDelMusicConstMeta,
      argValues: [that, musicList, ids],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWDelMusicConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_del_music",
        argNames: ["that", "musicList", "ids"],
      );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWDelMusicListTable(
      {required SqlMusicFactoryW that, required List<MusicList> musicLists}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_list_music_list(musicLists, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWDelMusicListTableConstMeta,
      argValues: [that, musicLists],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiMusicSdkSqlMusicFactoryWDelMusicListTableConstMeta =>
          const TaskConstMeta(
            debugName: "SqlMusicFactoryW_del_music_list_table",
            argNames: ["that", "musicLists"],
          );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWInitCreateTable(
      {required SqlMusicFactoryW that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWInitCreateTableConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWInitCreateTableConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_init_create_table",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWInsertMusic(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required List<MusicW> musics}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_box_autoadd_music_list(musicList, serializer);
        sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            musics, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWInsertMusicConstMeta,
      argValues: [that, musicList, musics],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWInsertMusicConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_insert_music",
        argNames: ["that", "musicList", "musics"],
      );

  @override
  Future<List<MusicW>> crateApiMusicSdkSqlMusicFactoryWReadMusic(
      {required SqlMusicFactoryW that, required MusicList musicList}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_box_autoadd_music_list(musicList, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWReadMusicConstMeta,
      argValues: [that, musicList],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWReadMusicConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_read_music",
        argNames: ["that", "musicList"],
      );

  @override
  Future<List<MusicW>> crateApiMusicSdkSqlMusicFactoryWReadMusicData(
      {required SqlMusicFactoryW that, required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWReadMusicDataConstMeta,
      argValues: [that, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWReadMusicDataConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_read_music_data",
        argNames: ["that", "source"],
      );

  @override
  Future<List<MusicList>> crateApiMusicSdkSqlMusicFactoryWReadMusicLists(
      {required SqlMusicFactoryW that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_music_list,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWReadMusicListsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWReadMusicListsConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_read_music_lists",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiMusicSdkSqlMusicFactoryWReorderMusic(
      {required SqlMusicFactoryW that,
      required MusicList musicList,
      required Int64List newIndex,
      required List<MusicW> oldMusicsInOrder}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            that, serializer);
        sse_encode_box_autoadd_music_list(musicList, serializer);
        sse_encode_list_prim_i_64_strict(newIndex, serializer);
        sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            oldMusicsInOrder, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSqlMusicFactoryWReorderMusicConstMeta,
      argValues: [that, musicList, newIndex, oldMusicsInOrder],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSqlMusicFactoryWReorderMusicConstMeta =>
      const TaskConstMeta(
        debugName: "SqlMusicFactoryW_reorder_music",
        argNames: ["that", "musicList", "newIndex", "oldMusicsInOrder"],
      );

  @override
  Future<List<MusicW>> crateApiMusicSdkGetMusicsFromMusicList(
      {required String payload, required int page, required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(payload, serializer);
        sse_encode_u_32(page, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkGetMusicsFromMusicListConstMeta,
      argValues: [payload, page, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkGetMusicsFromMusicListConstMeta =>
      const TaskConstMeta(
        debugName: "get_musics_from_music_list",
        argNames: ["payload", "page", "source"],
      );

  @override
  Future<(MusicList, List<MusicW>)> crateApiMusicSdkSearchAlbum(
      {required MusicW music, required int page}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            music, serializer);
        sse_encode_u_32(page, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_record_music_list_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_music_w,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSearchAlbumConstMeta,
      argValues: [music, page],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSearchAlbumConstMeta =>
      const TaskConstMeta(
        debugName: "search_album",
        argNames: ["music", "page"],
      );

  @override
  Future<List<MusicW>> crateApiMusicSdkSearchMusic(
      {required String content, required int page, required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_u_32(page, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSearchMusicConstMeta,
      argValues: [content, page, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSearchMusicConstMeta =>
      const TaskConstMeta(
        debugName: "search_music",
        argNames: ["content", "page", "source"],
      );

  @override
  Future<List<(String, MusicList)>> crateApiMusicSdkSearchMusicList(
      {required String content, required int page, required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_u_32(page, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_record_string_music_list,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMusicSdkSearchMusicListConstMeta,
      argValues: [content, page, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMusicSdkSearchMusicListConstMeta =>
      const TaskConstMeta(
        debugName: "search_music_list",
        argNames: ["content", "page", "source"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_MusicW => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_MusicW => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_PoolAny => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_PoolAny => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_SqlMusicFactoryW => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_SqlMusicFactoryW => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MusicW
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MusicWImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PoolAny
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PoolAnyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SqlMusicFactoryW
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SqlMusicFactoryWImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MusicW
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MusicWImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SqlMusicFactoryW
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SqlMusicFactoryWImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_string(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  MusicW
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MusicWImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PoolAny
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PoolAnyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SqlMusicFactoryW
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SqlMusicFactoryWImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Config dco_decode_box_autoadd_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_config(raw);
  }

  @protected
  MusicList dco_decode_box_autoadd_music_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_music_list(raw);
  }

  @protected
  Quality dco_decode_box_autoadd_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_quality(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Config dco_decode_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Config(
      userAgreement: dco_decode_bool(arr[0]),
      externApiPath: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<MusicW>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW)
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MusicInfo> dco_decode_list_music_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_music_info).toList();
  }

  @protected
  List<MusicList> dco_decode_list_music_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_music_list).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Quality> dco_decode_list_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_quality).toList();
  }

  @protected
  List<(String, MusicList)> dco_decode_list_record_string_music_list(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_music_list)
        .toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  MusicInfo dco_decode_music_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return MusicInfo(
      id: dco_decode_i_64(arr[0]),
      source: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      artist: dco_decode_list_String(arr[3]),
      duration: dco_decode_opt_box_autoadd_u_32(arr[4]),
      album: dco_decode_opt_String(arr[5]),
      qualities: dco_decode_list_quality(arr[6]),
      defaultQuality: dco_decode_opt_box_autoadd_quality(arr[7]),
      artPic: dco_decode_opt_String(arr[8]),
      lyric: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  MusicList dco_decode_music_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MusicList(
      name: dco_decode_String(arr[0]),
      artPic: dco_decode_String(arr[1]),
      desc: dco_decode_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Quality? dco_decode_opt_box_autoadd_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_quality(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Quality dco_decode_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Quality(
      short: dco_decode_String(arr[0]),
      level: dco_decode_opt_String(arr[1]),
      bitrate: dco_decode_opt_box_autoadd_u_32(arr[2]),
      format: dco_decode_opt_String(arr[3]),
      size: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  (
    SqlMusicFactoryW,
    Config
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_sql_music_factory_w_config(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          arr[0]),
      dco_decode_config(arr[1]),
    );
  }

  @protected
  (
    MusicList,
    List<MusicW>
  ) dco_decode_record_music_list_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_music_w(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_music_list(arr[0]),
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          arr[1]),
    );
  }

  @protected
  (String, MusicList) dco_decode_record_string_music_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_music_list(arr[1]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MusicW
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MusicWImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PoolAny
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PoolAnyImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SqlMusicFactoryW
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SqlMusicFactoryWImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MusicW
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MusicWImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SqlMusicFactoryW
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SqlMusicFactoryWImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Map<String, String> sse_decode_Map_String_String(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  MusicW
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MusicWImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PoolAny
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PoolAnyImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  SqlMusicFactoryW
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SqlMusicFactoryWImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Config sse_decode_box_autoadd_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_config(deserializer));
  }

  @protected
  MusicList sse_decode_box_autoadd_music_list(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_music_list(deserializer));
  }

  @protected
  Quality sse_decode_box_autoadd_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_quality(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Config sse_decode_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userAgreement = sse_decode_bool(deserializer);
    var var_externApiPath = sse_decode_opt_String(deserializer);
    return Config(
        userAgreement: var_userAgreement, externApiPath: var_externApiPath);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<MusicW>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MusicW>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
          sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
              deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MusicInfo> sse_decode_list_music_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MusicInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_music_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MusicList> sse_decode_list_music_list(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MusicList>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_music_list(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Quality> sse_decode_list_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Quality>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_quality(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, MusicList)> sse_decode_list_record_string_music_list(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, MusicList)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_music_list(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  MusicInfo sse_decode_music_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_artist = sse_decode_list_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_qualities = sse_decode_list_quality(deserializer);
    var var_defaultQuality = sse_decode_opt_box_autoadd_quality(deserializer);
    var var_artPic = sse_decode_opt_String(deserializer);
    var var_lyric = sse_decode_opt_String(deserializer);
    return MusicInfo(
        id: var_id,
        source: var_source,
        name: var_name,
        artist: var_artist,
        duration: var_duration,
        album: var_album,
        qualities: var_qualities,
        defaultQuality: var_defaultQuality,
        artPic: var_artPic,
        lyric: var_lyric);
  }

  @protected
  MusicList sse_decode_music_list(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_artPic = sse_decode_String(deserializer);
    var var_desc = sse_decode_String(deserializer);
    return MusicList(name: var_name, artPic: var_artPic, desc: var_desc);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Quality? sse_decode_opt_box_autoadd_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_quality(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Quality sse_decode_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_short = sse_decode_String(deserializer);
    var var_level = sse_decode_opt_String(deserializer);
    var var_bitrate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_format = sse_decode_opt_String(deserializer);
    var var_size = sse_decode_opt_String(deserializer);
    return Quality(
        short: var_short,
        level: var_level,
        bitrate: var_bitrate,
        format: var_format,
        size: var_size);
  }

  @protected
  (
    SqlMusicFactoryW,
    Config
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_sql_music_factory_w_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 =
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
            deserializer);
    var var_field1 = sse_decode_config(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (
    MusicList,
    List<MusicW>
  ) sse_decode_record_music_list_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_music_w(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_music_list(deserializer);
    var var_field1 =
        sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
            deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, MusicList) sse_decode_record_string_music_list(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_music_list(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          MusicW self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MusicWImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
          PoolAny self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PoolAnyImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          SqlMusicFactoryW self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SqlMusicFactoryWImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          MusicW self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MusicWImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          SqlMusicFactoryW self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SqlMusicFactoryWImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void sse_encode_Map_String_String(
      Map<String, String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          MusicW self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MusicWImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPoolAny(
          PoolAny self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PoolAnyImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
          SqlMusicFactoryW self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as SqlMusicFactoryWImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_config(Config self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_music_list(
      MusicList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_music_list(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_quality(Quality self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_quality(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_config(Config self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.userAgreement, serializer);
    sse_encode_opt_String(self.externApiPath, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          List<MusicW> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
          item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_music_info(
      List<MusicInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_music_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_music_list(
      List<MusicList> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_music_list(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_quality(List<Quality> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_quality(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_music_list(
      List<(String, MusicList)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_music_list(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_music_info(MusicInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.artist, serializer);
    sse_encode_opt_box_autoadd_u_32(self.duration, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_list_quality(self.qualities, serializer);
    sse_encode_opt_box_autoadd_quality(self.defaultQuality, serializer);
    sse_encode_opt_String(self.artPic, serializer);
    sse_encode_opt_String(self.lyric, serializer);
  }

  @protected
  void sse_encode_music_list(MusicList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.artPic, serializer);
    sse_encode_String(self.desc, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_quality(
      Quality? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_quality(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_quality(Quality self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.short, serializer);
    sse_encode_opt_String(self.level, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrate, serializer);
    sse_encode_opt_String(self.format, serializer);
    sse_encode_opt_String(self.size, serializer);
  }

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_sql_music_factory_w_config(
          (SqlMusicFactoryW, Config) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSqlMusicFactoryW(
        self.$1, serializer);
    sse_encode_config(self.$2, serializer);
  }

  @protected
  void
      sse_encode_record_music_list_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_music_w(
          (MusicList, List<MusicW>) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_music_list(self.$1, serializer);
    sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicW(
        self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_music_list(
      (String, MusicList) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_music_list(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class MusicWImpl extends RustOpaque implements MusicW {
  // Not to be used by end users
  MusicWImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MusicWImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MusicW,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MusicW,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MusicWPtr,
  );

  String getExtraInto({required Quality quality}) => RustLib.instance.api
      .crateApiMusicSdkMusicWGetExtraInto(that: this, quality: quality);

  PlatformInt64 getMusicId() =>
      RustLib.instance.api.crateApiMusicSdkMusicWGetMusicId(
        that: this,
      );

  MusicInfo getMusicInfo() =>
      RustLib.instance.api.crateApiMusicSdkMusicWGetMusicInfo(
        that: this,
      );
}

@sealed
class PoolAnyImpl extends RustOpaque implements PoolAny {
  // Not to be used by end users
  PoolAnyImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PoolAnyImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PoolAny,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PoolAny,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PoolAnyPtr,
  );
}

@sealed
class SqlMusicFactoryWImpl extends RustOpaque implements SqlMusicFactoryW {
  // Not to be used by end users
  SqlMusicFactoryWImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SqlMusicFactoryWImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SqlMusicFactoryW,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SqlMusicFactoryW,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_SqlMusicFactoryWPtr,
  );

  Future<void> changeMusicData(
          {required List<MusicW> musics, required List<MusicInfo> infos}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWChangeMusicData(
          that: this, musics: musics, infos: infos);

  Future<void> changeMusicDefaultSource(
          {required MusicList musicList,
          required Int64List ids,
          required List<String> defaultSources}) =>
      RustLib.instance.api
          .crateApiMusicSdkSqlMusicFactoryWChangeMusicDefaultSource(
              that: this,
              musicList: musicList,
              ids: ids,
              defaultSources: defaultSources);

  Future<void> changeMusicListMetadata(
          {required List<MusicList> oldList,
          required List<MusicList> newList}) =>
      RustLib.instance.api
          .crateApiMusicSdkSqlMusicFactoryWChangeMusicListMetadata(
              that: this, oldList: oldList, newList: newList);

  Future<void> cleanUnusedMusicData() =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWCleanUnusedMusicData(
        that: this,
      );

  Future<void> createMusicListTable({required List<MusicList> musicLists}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWCreateMusicListTable(
          that: this, musicLists: musicLists);

  Future<void> delMusic(
          {required MusicList musicList, required Int64List ids}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWDelMusic(
          that: this, musicList: musicList, ids: ids);

  Future<void> delMusicListTable({required List<MusicList> musicLists}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWDelMusicListTable(
          that: this, musicLists: musicLists);

  Future<void> initCreateTable() =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWInitCreateTable(
        that: this,
      );

  Future<void> insertMusic(
          {required MusicList musicList, required List<MusicW> musics}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWInsertMusic(
          that: this, musicList: musicList, musics: musics);

  Future<List<MusicW>> readMusic({required MusicList musicList}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWReadMusic(
          that: this, musicList: musicList);

  Future<List<MusicW>> readMusicData({required String source}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWReadMusicData(
          that: this, source: source);

  Future<List<MusicList>> readMusicLists() =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWReadMusicLists(
        that: this,
      );

  Future<void> reorderMusic(
          {required MusicList musicList,
          required Int64List newIndex,
          required List<MusicW> oldMusicsInOrder}) =>
      RustLib.instance.api.crateApiMusicSdkSqlMusicFactoryWReorderMusic(
          that: this,
          musicList: musicList,
          newIndex: newIndex,
          oldMusicsInOrder: oldMusicsInOrder);
}
