// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> urlEncodeSpecialChars({required String input}) =>
    RustLib.instance.api
        .crateApiUtilsPathUtilUrlEncodeSpecialChars(input: input);

Future<String> getLogDir({required String documentDir}) => RustLib.instance.api
    .crateApiUtilsPathUtilGetLogDir(documentDir: documentDir);

Future<String> getApprhymeDir({required String documentDir}) =>
    RustLib.instance.api
        .crateApiUtilsPathUtilGetApprhymeDir(documentDir: documentDir);
