// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `copy_data`

Future<void> moveCacheData(
        {required String documentPath,
        String? oldCustomCacheRoot,
        String? newCustomCacheRoot}) =>
    RustLib.instance.api.crateApiCacheCacheOpMoveCacheData(
        documentPath: documentPath,
        oldCustomCacheRoot: oldCustomCacheRoot,
        newCustomCacheRoot: newCustomCacheRoot);

Future<void> delOldCacheData(
        {required String documentPath, String? oldCustomCacheRoot}) =>
    RustLib.instance.api.crateApiCacheCacheOpDelOldCacheData(
        documentPath: documentPath, oldCustomCacheRoot: oldCustomCacheRoot);
