// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> genHash({required String str}) =>
    RustLib.instance.api.crateApiCacheFileCacheGenHash(str: str);

/// cache file
/// uri: file path or url
/// filename: file name, if None, use hash value
/// custom_root: custom storage path, if None, use root path of the app
Future<String> cacheFileFromUri(
        {required String uri,
        required String cacheFolder,
        String? filename,
        String? customRoot}) =>
    RustLib.instance.api.crateApiCacheFileCacheCacheFileFromUri(
        uri: uri,
        cacheFolder: cacheFolder,
        filename: filename,
        customRoot: customRoot);

/// cache file from content
/// content: file content
/// filename: file name
/// custom_root: custom storage path, if None, use root path of the app
Future<String> cacheFileFromContent(
        {required String content,
        required String cacheFolder,
        required String filename,
        String? customRoot}) =>
    RustLib.instance.api.crateApiCacheFileCacheCacheFileFromContent(
        content: content,
        cacheFolder: cacheFolder,
        filename: filename,
        customRoot: customRoot);

String? getCacheFileFromUri(
        {required String uri,
        required String cacheFolder,
        String? filename,
        required String root,
        String? customRoot}) =>
    RustLib.instance.api.crateApiCacheFileCacheGetCacheFileFromUri(
        uri: uri,
        cacheFolder: cacheFolder,
        filename: filename,
        root: root,
        customRoot: customRoot);

Future<void> deleteCacheFileWithUri(
        {required String uri,
        required String cacheFolder,
        String? filename,
        String? customRoot}) =>
    RustLib.instance.api.crateApiCacheFileCacheDeleteCacheFileWithUri(
        uri: uri,
        cacheFolder: cacheFolder,
        filename: filename,
        customRoot: customRoot);
