// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../music_api/mirror.dart';
import '../types/playinfo.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_music_file_name`, `gen_music_meta_file_path`, `get_lyric_file_name`

Future<bool> hasCacheMusic({required Music music}) =>
    RustLib.instance.api.crateApiCacheMusicCacheHasCacheMusic(music: music);

/// get cached music lyric and playinfo
Future<(PlayInfo, String)?> getCacheMusic({required Music music}) =>
    RustLib.instance.api.crateApiCacheMusicCacheGetCacheMusic(music: music);

Future<void> cacheMusic(
        {required Music musicInfo,
        required PlayInfo playinfo,
        String? lyric}) =>
    RustLib.instance.api.crateApiCacheMusicCacheCacheMusic(
        musicInfo: musicInfo, playinfo: playinfo, lyric: lyric);

Future<void> deleteMusicCache({required Music musicInfo}) =>
    RustLib.instance.api
        .crateApiCacheMusicCacheDeleteMusicCache(musicInfo: musicInfo);
