// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> setDb({required String databaseUrl}) =>
    RustLib.instance.api.crateApiMusicApiFnsSetDb(databaseUrl: databaseUrl);

Future<bool> dbInited() => RustLib.instance.api.crateApiMusicApiFnsDbInited();

Future<void> closeDb() => RustLib.instance.api.crateApiMusicApiFnsCloseDb();
