// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DatabaseJsonWrapper>>
abstract class DatabaseJsonWrapper implements RustOpaqueInterface {
  /// takes ownership
  Future<void> applyToDb();

  static Future<DatabaseJsonWrapper> fromJson({required String json}) =>
      RustLib.instance.api
          .crateApiMusicApiWrapperDatabaseJsonWrapperFromJson(json: json);

  static Future<DatabaseJsonWrapper> getFromDb() => RustLib.instance.api
      .crateApiMusicApiWrapperDatabaseJsonWrapperGetFromDb();

  static Future<DatabaseJsonWrapper> loadFrom({required String path}) =>
      RustLib.instance.api
          .crateApiMusicApiWrapperDatabaseJsonWrapperLoadFrom(path: path);

  Future<void> saveTo({required String path});

  Future<String> toJson();
}
