// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_user_agreement`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `default`

class Config {
  final bool userAgreement;
  final String? externApiPath;

  const Config({
    required this.userAgreement,
    this.externApiPath,
  });

  static Future<Config> load() =>
      RustLib.instance.api.crateApiConfigConfigLoad();

  Future<void> save() => RustLib.instance.api.crateApiConfigConfigSave(
        that: this,
      );

  @override
  int get hashCode => userAgreement.hashCode ^ externApiPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          userAgreement == other.userAgreement &&
          externApiPath == other.externApiPath;
}
