// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types/config.dart';
import 'types/external_api.dart';

Future<Config> initBackend({required String documentFolder}) =>
    RustLib.instance.api
        .crateApiInitInitBackend(documentFolder: documentFolder);
