name: "build_android"
on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable 
      - run: flutter build apk --release
      - run: flutter build apk --release --split-per-abi
      - name: Rename Apks
        run: |
            mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/AppRhyme_android_unknown.apk
            mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/AppRhyme_android_armeabi-v7a.apk
            mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/AppRhyme_android_arm64-v8a.apk
            mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/AppRhyme_android_x86_64.apk
      - name: Upload Apks
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/app/outputs/flutter-apk/AppRhyme_android_unknown.apk
            build/app/outputs/flutter-apk/AppRhyme_android_armeabi-v7a.apk
            build/app/outputs/flutter-apk/AppRhyme_android_arm64-v8a.apk
            build/app/outputs/flutter-apk/AppRhyme_android_x86_64.apk
          compression-level: 9